name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f1001826@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Run a script
        run: echo "This is a test workflow."
